### PR TITLE
EventArgs example

### PR DESCRIPTION
**Pull request by samklop**
Adds an [EventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.eventargs?view=net-5.0) example to the repo.

### CODE REVIEW

**Comment by Schmitzenbergh** [comment]
Great example! Is it possible to integrate this with the existing EventExample? Maybe add some extra information to a shape.
This way we can keep examples that are related to eachother in one project.

**Comment by samklop** [comment]
> Great example! Is it possible to integrate this with the existing EventExample? Maybe add some extra information to a shape.
> This way we can keep examples that are related to eachother in one project.

A private property, or field could be passed through the EventArgs, I was thinking maybe this could be a string called description for the rectangle class provided in the EventExample.

**Comment by Schmitzenbergh** [comment]
Something like that is fine. Just fork the project and make the changes to the EventExample project.

**Comment by samklop** [comment]
When setting the description should this also call the `EventHandler` ?

**Comment by Schmitzenbergh** [comment]
I have no real intention on how to demonstrate the EventArgs, as long as they are showed in an understandable manner for other students. So feel free on how you integrate it. If it is not really my liking but the message is clear, I will clarify it 👍

**Comment by samklop** [comment]
> I have no real intention on how to demonstrate the EventArgs, as long as they are showed in an understandable manner for other students. So feel free on how you integrate it. If it is not really my liking but the message is clear, I will clarify it 👍

I have committed the changes, feel free to take a look!

**Review by Schmitzenbergh — APPROVED** [review]
Looks good. Thank you! I will merge this into the master.

**Pull request merged**
